HARI PAVAN YADAV AMB2080

In [ ]:
import pandas as pd

production=pd.Series(
    [30,60,45,25],
    index=["Wheat","Rice","Maize","Barley"]
)
print(production)

Wheat     30
Rice      60
Maize     45
Barley    25
dtype: int64

In [ ]:
#by crop name
print(production["Rice"])
print(production.loc["Rice"])

60
60

In [ ]:
#by position
print(production.iloc[0])

30

In [6]:
print(production.sum())
print(production.mean())
print(production.max())
print(production.min())
print(production.idxmax())  #maixmum production crop
#it prints the index label of the maximum value in the series

160
40.0
60
25
Rice

In [4]:
import pandas as pd

production=pd.Series(
    [30,60,45,25],
    index=["Wheat","Rice","Maize","Barley"]
)

#crops with the production greater than 40 tons
high_production=production[production>40]
print(high_production)
print()

Rice     60
Maize    45
dtype: int64

In [ ]:
import pandas as pd
df=pd.DataFrame({
    "name":["Akhil","Bobby","Charan"],
    "age":[25,30,35],
    "city":["NY","LS","chicago"],
},index=["a","b","c"])
print(df)
print()
print(df.loc["b"])

     name  age     city
a   Akhil   25       NY
b   Bobby   30       LS
c  Charan   35  chicago

name    Bobby
age        30
city       LS
Name: b, dtype: object

In [ ]:
print(df)
print()
print(df.loc[["a","c"],["name","city"]])

     name  age     city
a   Akhil   25       NY
b   Bobby   30       LS
c  Charan   35  chicago

     name     city
a   Akhil       NY
c  Charan  chicago

In [ ]:
print(df.loc["a":"c"])
print(df.iloc[0:2])

     name  age     city
a   Akhil   25       NY
b   Bobby   30       LS
c  Charan   35  chicago
    name  age city
a  Akhil   25   NY
b  Bobby   30   LS

11-02-2026

In [ ]:
print(df.loc[df["age"]>])

In [ ]:
import pandas as pd
df=pd.DataFrame({
    "name":["Akhil","Bobby","Charan"],
    "age":[25,30,35],
    "city":["NY","LS","chicago"],
},index=["a","b","c"])
print(df)
print()
print(df.iloc[1])

     name  age     city
a   Akhil   25       NY
b   Bobby   30       LS
c  Charan   35  chicago

name    Bobby
age        30
city       LS
Name: b, dtype: object

In [ ]:
print(df.iloc[1])

name    Bobby
age        30
city       LS
Name: b, dtype: object

In [ ]:
print(df.iloc[[0,2],[1,2]])

   age     city
a   25       NY
c   35  chicago

In [ ]:
import pandas as pd
df=pd.DataFrame({
    "name":["Akhil","Bobby","Charan"],
    "age":[25,30,35],
    "city":["NY","LS","chicago"],
},index=["a","b","c"])
print(df)
print()
df.iloc[[0:2]]

In [ ]:
df["name"]

a     Akhil
b     Bobby
c    Charan
Name: name, dtype: object

In [ ]:
df[["name","age"]]

     name  age
a   Akhil   25
b   Bobby   30
c  Charan   35

In [ ]:
import pandas as pd
data={
    "Farm":["Farm A","Farm B","Farm C","Farm D"],
    "Crop":["Wheat","Rice","Wheat","Maize"],
    "Area_hectares":[10,15,8,12],
    "Production_tons":[30,60,24,36]
}
df=pd.DataFrame(data)
print(df)

     Farm   Crop  Area_hectares  Production_tons
0  Farm A  Wheat             10               30
1  Farm B   Rice             15               60
2  Farm C  Wheat              8               24
3  Farm D  Maize             12               36

In [ ]:
df.tail(2)

     Farm   Crop  Area_hectares  Production_tons
2  Farm C  Wheat              8               24
3  Farm D  Maize             12               36

In [ ]:
df.head(5)

     Farm   Crop  Area_hectares  Production_tons
0  Farm A  Wheat             10               30
1  Farm B   Rice             15               60
2  Farm C  Wheat              8               24
3  Farm D  Maize             12               36

In [3]:
import pandas as pd
data={
    "Farm":["Farm A","Farm B","Farm C","Farm D"],
    "Crop":["Wheat","Rice","Wheat","Maize"],
    "Area_hectares":[10,15,8,12],
    "Production_tons":[30,60,24,36]
}
df=pd.DataFrame(data)

df["yield_ton_per_hectare"]=df["Production_tons"]/df["Area_hectares"]
print(df)

     Farm   Crop  Area_hectares  Production_tons  yield_ton_per_hectare
0  Farm A  Wheat             10               30                    3.0
1  Farm B   Rice             15               60                    4.0
2  Farm C  Wheat              8               24                    3.0
3  Farm D  Maize             12               36                    3.0

In [ ]:
df.iloc[[1,3]]

     Farm   Crop  Area_hectares  Production_tons
1  Farm B   Rice             15               60
3  Farm D  Maize             12               36

In [ ]:
df.iloc[[1,3][0:3]]

     Farm   Crop  Area_hectares  Production_tons
1  Farm B   Rice             15               60
3  Farm D  Maize             12               36

In [ ]:
print([df["Crop"]=="Wheat"])
print()
wheat_farms=df[df["Crop"]=="Wheat"]
print(wheat_farms)

[0     True
1    False
2     True
3    False
Name: Crop, dtype: bool]

     Farm   Crop  Area_hectares  Production_tons
0  Farm A  Wheat             10               30
2  Farm C  Wheat              8               24

In [ ]:
#sort farms by highest production
sorted_df=df.sort_values(by="production_tons")

In [ ]:
#groupby operation - average yield per crop
avg_yield=df.groupby("Crop")["yield_ton_per_hectare"].mean()
print(avg_yield)

KeyError: 'Column not found: yield_ton_per_hectare'